name: "Open WebUI"
description: "Open WebUI for Home Assistant with remote Ollama support"
version: "latest"
slug: "open_webui"
arch:
  - aarch64
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
host_network: true
ports:
  8080/tcp: 8080
map:
  - config:rw
  - share
options: {}
schema: {}
image: ghcr.io/mikastamm/open-webui-hass
