name: "Open WebUI"
description: "Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI platform designed to operate entirely offline"
url: https://github.com/mikastamm/open-webui-homeassistant-addon
version: "v0.6.15"
slug: "openwebui"
panel_icon: mdi:message
init: false
ingress: true
ingress_port: 8080

arch:
  - aarch64
  - amd64
startup: services
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Open WebUI Web Interface"
map:
  - share
options:
  PGID: 0
  PUID: 0
schema:
  PGID: "int"
  PUID: "int"
  TZ: "str?"
image: ghcr.io/mikastamm/open-webui-homeassistant-addon
