name: "Open WebUI"
description: "Open WebUI is an extensible, feature-rich, and user-friendly self-hosted AI platform designed to operate entirely offline"
url: https://github.com/mikastamm/open-webui-homeassistant-addon
version: "v0.6.15"
slug: "openwebui"
panel_icon: mdi:message
init: false
ingress: true
ingress_entry: "openwebui"
panel_iframe: true

arch:
  - aarch64
  - amd64
startup: services
ports:
  8080/tcp: null
ports_description:
  8080/tcp: "Open WebUI Web Interface"
map:
  - share
options:
  PGID: 0
  PUID: 0
  connection_mode: "ingress_noauth"
schema:
  PGID: "int"
  PUID: "int"
  TZ: "str?"
  connection_mode: "list(ingress_noauth|noingress_auth|ingress_auth)"
image: ghcr.io/mikastamm/open-webui-homeassistant-addon
